version: '3.4'

services:

  imagination.server:
    image: imaginationserverapi
    build:
      context: .
      dockerfile: src/Imagination.Server/Dockerfile      
    depends_on:
      - jaeger
      - httpbin
    ports:
      - "5000:80"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14268:14268/tcp"
      - "14250:14250/tcp"
      - "16686:16686"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
